### ISSUE TITLE
I cant log in as receptionists

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#11]
**Area**: User Interface
**Severity**: high
**Priority**: high
**Environment**:/Development
**Build number**: latest in production
**Steps to reproduce**:
Go to https://fitness-club.herokuapp.com/receptionists/sign_in
**Actual result**: Website doesn't response
**Expected result**: Log in panel should be open

**Comment by pikpok** [comment]
we changed admin and receptionist path to /admin and /receptionist
