### ISSUE TITLE
Admins log in site doesn't work

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#12]
**Area**: Backend
**Severity**: high
**Priority**: high
**Environment**:Development
**Build number**: latest in production
**Steps to reproduce**:
Go to https://fitness-club.herokuapp.com/admins/sign_in
**Actual result** Website doesn't work
**Expected result**: Log in panel should be opened

**Comment by pikpok** [comment]
we changed admin and receptionist path to /admin and /receptionist
