### ISSUE TITLE
User sign in website doesn't run from facebook chat

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#13]
**Area**: User Interface
**Severity**: low
**Priority**: low
**Environment**: Development
**Build number**: latest in production1
**Steps to reproduce**:
Click https://fitness-club.herokuapp.com/user/sign_in in facebook chat
**Actual result**: website wont work
**Expected result**: website log in form

**Comment by pikpok** [comment]
can't reproduce, for me it's working :)
