### ISSUE TITLE
Website is crashed after adding new receptionist

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#22]
**Area**: Backend
**Severity**: high
**Priority**: high
**Environment**: Production
**Build number**:"latest in production
**Steps to reproduce**:
1.Log in as admin
2.Go to receptionist panel
3.Add receptionist
4.Write a name same as receptionist which already exists
**Actual result**: Website crashes
**Expected result**: Should get warning receptionist exists

**Comment by pikpok** [comment]
fixed in 4f4746332d26ff3a9abfa593c6abf7397c11af52
