### ISSUE TITLE
Receptionist password issue

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#26]
**Area**: Backend
**Severity**: medium
**Priority**:medium
**Environment**: Production
**Build number**: latest in production
**Steps to reproduce**:
1.Log in as admin
2.Click manage receptionist
3.Click receptionist
4.Change password
5.Write password
6.Write bad confirmation password

**Actual result**: Receptionist password is updated
**Expected result**: Receptionist password shouldn't be updated

**Comment by pikpok** [comment]
fixed in 4f4746332d26ff3a9abfa593c6abf7397c11af52
