### ISSUE TITLE
Receptionist password cant be updated

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#27]
**Area**: Backend
**Severity**:medium
**Priority**: medium
**Environment**: Production
**Build number**:latest in production
**Steps to reproduce**:
1.Log in as admin
2.Click manage receptionist
3.Click receptionist
4.Change password/update
5.Go to receptionist log in panel
6.Put log in
7.Put new password
**Actual result**: password doesn't fix
**Expected result**: Log in as receptionist.

**Comment by pikpok** [comment]
fixed in 4f4746332d26ff3a9abfa593c6abf7397c11af52
