### ISSUE TITLE
Multiple click on icon cause delay

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#9]
**Area**:User Interface
**Severity**: medium
**Priority**:medium
**Environment**:Development
**Build number**: latest in production
**Steps to reproduce**:
1.Multiple fast click on icon
**Actual result**:Icon doesn't response or response after 20s.
**Expected result**:Icon should redirect me to proper website

**Comment by pikpok** [comment]
I can't reproduce it, closing
